import type { Metadata } from "next";
import { Hedvig_Letters_Sans } from "next/font/google";
import "./globals.css";

const hedvig = Hedvig_Letters_Sans({
  subsets: ["latin"],
  weight: "400", // regular
  variable: "--font-hedvig",
});

export const metadata: Metadata = {
  title: "Maa's Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hedvig.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
